camunda.bpm:
  metrics.enabled: false
  history-level: auto

  database:
    schema-update: false
    type: mysql

spring.datasource:
  url: jdbc:mysql://localhost:3306/CUGHH?useSSL=false
  username: camunda
  password: camunda
  driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8081

